//! ビルド時に layout/naginata.yaml を読み、phf テーブルを含む Rust ソースを生成する。
//! 生成物: $OUT_DIR/keymap_gen.rs （src/keymap.rs から include!）
//!
//! モデル: 出力 = LAYERS[(mask<<8)|sc] （詳細設計 A.5/B.2）。実行時パース無し。

use serde::Deserialize;
use std::collections::HashMap;
use std::env;
use std::fs;
use std::io::Write;
use std::path::Path;

#[derive(Deserialize)]
struct Layout {
    window_ms: u32,
    tap_ms: u32,
    shifts: Vec<ShiftDef>,
    layers: Vec<LayerDef>,
    #[serde(default)]
    combo2: Vec<Combo2Def>,
    #[serde(default)]
    combo3: Vec<Combo3Def>,
    #[serde(default)]
    modes: Vec<ModeDef>,
    matrix_left: Vec<MatrixPos>,
    matrix_right: Vec<MatrixPos>,
}

/// 編集モード（2キートリガで持続モード→後続キーを編集アクションへ）。
#[derive(Deserialize)]
struct ModeDef {
    id: u8,
    trigger: Vec<u8>, // 2要素
    map: Vec<KeysEntry>,
}

/// 2キー同時押しコンボ（非シフト2キー: 清音拗音 等）。
#[derive(Deserialize)]
struct Combo2Def {
    keys: Vec<u8>, // 2要素
    k: String,
}

/// 3キー同時押しコンボ（外来音・濁音拗音等）。
#[derive(Deserialize)]
struct Combo3Def {
    keys: Vec<u8>, // 3要素
    k: String,
}

#[derive(Deserialize)]
struct ShiftDef {
    name: String,
    sc: u8,
    bit: u8,
}

#[derive(Deserialize)]
struct LayerDef {
    when: Vec<String>,
    #[serde(default)]
    kana: Vec<KanaEntry>,
    #[serde(default)]
    keys: Vec<KeysEntry>,
}

#[derive(Deserialize)]
struct KanaEntry {
    sc: u8,
    k: String,
}

#[derive(Deserialize)]
struct KeysEntry {
    sc: u8,
    syms: Vec<String>,
}

#[derive(Deserialize)]
struct MatrixPos {
    row: u8,
    col: u8,
    sc: u8,
}

/// シフトシンボル名 → mask ビット（1<<bit）。
fn build_shift_map(shifts: &[ShiftDef]) -> HashMap<String, u8> {
    shifts
        .iter()
        .map(|s| (s.name.clone(), 1u8 << s.bit))
        .collect()
}

/// when（シフト名集合）→ ShiftMask(u8) を bitOR で合成。
fn mask_of(when: &[String], shift_map: &HashMap<String, u8>) -> u8 {
    when.iter()
        .map(|n| {
            *shift_map
                .get(n)
                .unwrap_or_else(|| panic!("unknown shift name in `when`: {n}"))
        })
        .fold(0u8, |a, b| a | b)
}

/// LAYERS のキー: (mask<<8)|sc を u16 にパック。
fn layer_key(mask: u8, sc: u8) -> u16 {
    ((mask as u16) << 8) | sc as u16
}

/// HID modifier ビット。
const CTRL: u8 = 0x01;
const SHIFT: u8 = 0x02;

/// HID シンボル名 → (usage, modifiers) 列。
/// `"NAME*N"` で N 回リピート（編集モードの選択 +{→ 20} 等）。
fn symbol_to_keys(sym: &str) -> Vec<(u8, u8)> {
    // リピート記法 NAME*N
    if let Some((name, count)) = sym.split_once('*') {
        let n: usize = count.trim().parse().unwrap_or_else(|_| panic!("bad repeat: {sym}"));
        let base = symbol_to_keys(name.trim());
        let mut out = Vec::with_capacity(base.len() * n);
        for _ in 0..n {
            out.extend_from_slice(&base);
        }
        return out;
    }
    use std::collections::BTreeMap;
    let table: BTreeMap<&str, (u8, u8)> = BTreeMap::from([
        ("LANG1", (0x90, 0)), // かな（IME ON）
        ("LANG2", (0x91, 0)), // 英数（IME OFF）
        ("Enter", (0x28, 0)),
        ("Esc", (0x29, 0)),
        ("BS", (0x2a, 0)),
        ("Tab", (0x2b, 0)),
        ("Space", (0x2c, 0)),
        ("Del", (0x4c, 0)),
        ("Home", (0x4a, 0)),
        ("End", (0x4d, 0)),
        ("Right", (0x4f, 0)),
        ("Left", (0x50, 0)),
        ("Down", (0x51, 0)),
        ("Up", (0x52, 0)),
        ("Comma", (0x36, 0)),  // , → IMEローマ字で 、
        ("Period", (0x37, 0)), // . → IMEローマ字で 。
        // Shift+（選択・カーソル）
        ("S-Left", (0x50, SHIFT)),
        ("S-Right", (0x4f, SHIFT)),
        ("S-Up", (0x52, SHIFT)),
        ("S-Down", (0x51, SHIFT)),
        ("S-Home", (0x4a, SHIFT)),
        ("S-End", (0x4d, SHIFT)),
        // Ctrl+（編集モードの定番）
        ("C-c", (0x06, CTRL)), // copy
        ("C-x", (0x1b, CTRL)), // cut
        ("C-v", (0x19, CTRL)), // paste
        ("C-y", (0x1c, CTRL)), // redo
        ("C-z", (0x1d, CTRL)), // undo
        ("C-i", (0x0c, CTRL)),
        ("C-u", (0x18, CTRL)),
        ("C-s", (0x16, CTRL)), // save
    ]);
    match table.get(sym) {
        Some(&kp) => vec![kp],
        None => panic!("unknown HID symbol: {sym}"),
    }
}

fn main() {
    let layout_path = "layout/naginata.yaml";
    println!("cargo:rerun-if-changed={layout_path}");
    println!("cargo:rerun-if-changed=build.rs");

    let text = fs::read_to_string(layout_path).expect("read layout yaml");
    let layout: Layout = serde_yaml::from_str(&text).expect("parse layout yaml");
    let shift_map = build_shift_map(&layout.shifts);

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("keymap_gen.rs");
    let mut f = fs::File::create(&dest).unwrap();

    writeln!(f, "// @generated by build.rs from {layout_path}").unwrap();
    writeln!(f, "pub const WINDOW_MS: u32 = {};", layout.window_ms).unwrap();
    writeln!(f, "pub const TAP_MS: u32 = {};", layout.tap_ms).unwrap();

    // SHIFT_KEYS: sc(u8) -> mask(u8, 1<<bit)
    let mut shift_keys = phf_codegen::Map::new();
    for s in &layout.shifts {
        shift_keys.entry(s.sc, &format!("{}u8", 1u8 << s.bit));
    }
    writeln!(
        f,
        "pub static SHIFT_KEYS: phf::Map<u8, u8> = {};",
        shift_keys.build()
    )
    .unwrap();

    // LAYERS: (mask<<8)|sc (u16) -> crate::Action
    let mut layers = phf_codegen::Map::new();
    // 重複キー検出用
    let mut seen: HashMap<u16, String> = HashMap::new();
    // 単打レイヤ(mask=0)の かな sc 一覧（#12: PC からの単打編集対象キー）。
    let mut single_tap_scs: Vec<u8> = Vec::new();
    for layer in &layout.layers {
        let mask = mask_of(&layer.when, &shift_map);
        for e in &layer.kana {
            let key = layer_key(mask, e.sc);
            check_dup(&mut seen, key, &layer.when);
            if mask == 0 {
                single_tap_scs.push(e.sc);
            }
            layers.entry(key, &format!("crate::Action::Kana(\"{}\")", e.k));
        }
        for e in &layer.keys {
            let key = layer_key(mask, e.sc);
            check_dup(&mut seen, key, &layer.when);
            let kps: Vec<String> = e
                .syms
                .iter()
                .flat_map(|s| symbol_to_keys(s))
                .map(|(u, m)| format!("crate::hid::KeyPress {{ usage: {u}u8, modifiers: {m}u8 }}"))
                .collect();
            layers.entry(
                key,
                &format!("crate::Action::Keys(&[{}])", kps.join(", ")),
            );
        }
    }
    writeln!(
        f,
        "pub static LAYERS: phf::Map<u16, crate::Action> = {};",
        layers.build()
    )
    .unwrap();

    // SINGLE_TAP_SCS: 単打レイヤ(mask=0)のかな sc 一覧（昇順・重複排除）。
    // #12: PC 設定ツールが編集可能な単打キーを列挙するのに使う。
    single_tap_scs.sort_unstable();
    single_tap_scs.dedup();
    let scs: Vec<String> = single_tap_scs.iter().map(|s| format!("{s}u8")).collect();
    writeln!(
        f,
        "pub static SINGLE_TAP_SCS: &[u8] = &[{}];",
        scs.join(", ")
    )
    .unwrap();

    // COMBO2: 非シフト2キー同時押し → Action。キー = sorted(min|max<<8) u16。
    let mut combo2 = phf_codegen::Map::new();
    for c in &layout.combo2 {
        assert!(c.keys.len() == 2, "combo2 は2キー: {:?}", c.keys);
        let key = combo2_pack(c.keys[0], c.keys[1]);
        combo2.entry(key, &format!("crate::Action::Kana(\"{}\")", c.k));
    }
    writeln!(
        f,
        "pub static COMBO2: phf::Map<u16, crate::Action> = {};",
        combo2.build()
    )
    .unwrap();

    // COMBO3: 3キー sorted(u32) → Action。PREFIX2: その2キー部分集合（遅延判定用）。
    let mut combo3 = phf_codegen::Map::new();
    let mut prefix2 = phf_codegen::Set::new();
    let mut prefix_seen: std::collections::HashSet<u16> = std::collections::HashSet::new();
    for c in &layout.combo3 {
        assert!(c.keys.len() == 3, "combo3 は3キー: {:?}", c.keys);
        let mut ks = [c.keys[0], c.keys[1], c.keys[2]];
        ks.sort_unstable();
        let packed = ks[0] as u32 | (ks[1] as u32) << 8 | (ks[2] as u32) << 16;
        combo3.entry(packed, &format!("crate::Action::Kana(\"{}\")", c.k));
        // 3つの2キー部分集合を prefix2 へ
        for &(a, b) in &[(ks[0], ks[1]), (ks[0], ks[2]), (ks[1], ks[2])] {
            let p2 = combo2_pack(a, b);
            if prefix_seen.insert(p2) {
                prefix2.entry(p2);
            }
        }
    }
    writeln!(
        f,
        "pub static COMBO3: phf::Map<u32, crate::Action> = {};",
        combo3.build()
    )
    .unwrap();
    writeln!(f, "pub static PREFIX2: phf::Set<u16> = {};", prefix2.build()).unwrap();

    // 編集モード: トリガ(sorted 2キー u16) → mode id / (mode<<8|sc) → Action::Keys
    let mut mtrig = phf_codegen::Map::new();
    let mut mlayers = phf_codegen::Map::new();
    for m in &layout.modes {
        assert!(m.trigger.len() == 2, "mode trigger は2キー: {:?}", m.trigger);
        mtrig.entry(combo2_pack(m.trigger[0], m.trigger[1]), &format!("{}u8", m.id));
        for e in &m.map {
            let key = ((m.id as u16) << 8) | e.sc as u16;
            let kps: Vec<String> = e
                .syms
                .iter()
                .flat_map(|s| symbol_to_keys(s))
                .map(|(u, md)| format!("crate::hid::KeyPress {{ usage: {u}u8, modifiers: {md}u8 }}"))
                .collect();
            mlayers.entry(key, &format!("crate::Action::Keys(&[{}])", kps.join(", ")));
        }
    }
    writeln!(f, "pub static MODE_TRIGGERS: phf::Map<u16, u8> = {};", mtrig.build()).unwrap();
    writeln!(
        f,
        "pub static MODE_LAYERS: phf::Map<u16, crate::Action> = {};",
        mlayers.build()
    )
    .unwrap();

    // MATRIX: 位置(row*16+col, u8) -> sc(u8)。手番ごと。
    write_matrix(&mut f, "MATRIX_LEFT", &layout.matrix_left);
    write_matrix(&mut f, "MATRIX_RIGHT", &layout.matrix_right);
}

/// 2キーを sorted で u16 にパック。keymap.rs の combo2_key と一致させること。
fn combo2_pack(a: u8, b: u8) -> u16 {
    let (lo, hi) = if a <= b { (a, b) } else { (b, a) };
    (lo as u16) | ((hi as u16) << 8)
}

fn check_dup(seen: &mut HashMap<u16, String>, key: u16, when: &[String]) {
    if let Some(prev) = seen.insert(key, format!("{when:?}")) {
        panic!(
            "duplicate (mask,sc) layer entry key=0x{key:04x}: {prev} と {when:?} が衝突"
        );
    }
}

fn write_matrix(f: &mut fs::File, name: &str, rows: &[MatrixPos]) {
    let mut m = phf_codegen::Map::new();
    for p in rows {
        let pos = (p.row << 4) | (p.col & 0x0f);
        m.entry(pos, &format!("{}u8", p.sc));
    }
    writeln!(f, "pub static {name}: phf::Map<u8, u8> = {};", m.build()).unwrap();
}
